/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SplitRouteImport } from './routes/split'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPilotRouteImport } from './routes/api/pilot'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPilotRoute = ApiPilotRouteImport.update({
  id: '/api/pilot',
  path: '/api/pilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/budget': typeof BudgetRoute
  '/earn': typeof EarnRoute
  '/history': typeof HistoryRoute
  '/pilot': typeof PilotRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/reminders': typeof RemindersRoute
  '/scan': typeof ScanRoute
  '/split': typeof SplitRoute
  '/transfer': typeof TransferRoute
  '/api/pilot': typeof ApiPilotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/budget': typeof BudgetRoute
  '/earn': typeof EarnRoute
  '/history': typeof HistoryRoute
  '/pilot': typeof PilotRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/reminders': typeof RemindersRoute
  '/scan': typeof ScanRoute
  '/split': typeof SplitRoute
  '/transfer': typeof TransferRoute
  '/api/pilot': typeof ApiPilotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/budget': typeof BudgetRoute
  '/earn': typeof EarnRoute
  '/history': typeof HistoryRoute
  '/pilot': typeof PilotRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/reminders': typeof RemindersRoute
  '/scan': typeof ScanRoute
  '/split': typeof SplitRoute
  '/transfer': typeof TransferRoute
  '/api/pilot': typeof ApiPilotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bills'
    | '/budget'
    | '/earn'
    | '/history'
    | '/pilot'
    | '/profile'
    | '/receive'
    | '/reminders'
    | '/scan'
    | '/split'
    | '/transfer'
    | '/api/pilot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bills'
    | '/budget'
    | '/earn'
    | '/history'
    | '/pilot'
    | '/profile'
    | '/receive'
    | '/reminders'
    | '/scan'
    | '/split'
    | '/transfer'
    | '/api/pilot'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bills'
    | '/budget'
    | '/earn'
    | '/history'
    | '/pilot'
    | '/profile'
    | '/receive'
    | '/reminders'
    | '/scan'
    | '/split'
    | '/transfer'
    | '/api/pilot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillsRoute: typeof BillsRoute
  BudgetRoute: typeof BudgetRoute
  EarnRoute: typeof EarnRoute
  HistoryRoute: typeof HistoryRoute
  PilotRoute: typeof PilotRoute
  ProfileRoute: typeof ProfileRoute
  ReceiveRoute: typeof ReceiveRoute
  RemindersRoute: typeof RemindersRoute
  ScanRoute: typeof ScanRoute
  SplitRoute: typeof SplitRoute
  TransferRoute: typeof TransferRoute
  ApiPilotRoute: typeof ApiPilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pilot': {
      id: '/api/pilot'
      path: '/api/pilot'
      fullPath: '/api/pilot'
      preLoaderRoute: typeof ApiPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillsRoute: BillsRoute,
  BudgetRoute: BudgetRoute,
  EarnRoute: EarnRoute,
  HistoryRoute: HistoryRoute,
  PilotRoute: PilotRoute,
  ProfileRoute: ProfileRoute,
  ReceiveRoute: ReceiveRoute,
  RemindersRoute: RemindersRoute,
  ScanRoute: ScanRoute,
  SplitRoute: SplitRoute,
  TransferRoute: TransferRoute,
  ApiPilotRoute: ApiPilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
